
<div class="infobox">
        <h2>{$forum->name}</h2>
        <div class="admin_controls">
            {if User::loggedIn()->isAdmin()}
            <a href="?controller=forums&do=edit&forum_id={$forum->forum_id}">
                <i class="fas fa-cog"></i>
            </a>
            <a href="?controller=forums&do=delete&forum_id={$forum->forum_id}">
                <i class="fas fa-trash"></i>
            </a>
            {/if}
            <a href="?controller=topics&do=add&forum_id={$forum->forum_id}" class="button">Nowy temat</a>
        </div>
</div>
{if count($topics)}
<ol class="topics">
    {foreach $topics as $topic}
        <li>
            <div class="topic_info">
                <h4>
                    <a href="{$topic->url()}">
                        {$topic->title}
                    </a>
                </h4>
                <div class="details">przez {$topic->author()->link()|noescape} &middot; napisano {$topic->created}</div>
            </div>
            <div class="posts_count">
                <div class="number">{$topic->countPosts()}</div> odpowiedzi
            </div>
            <div class="last_poster">
                {if $topic->lastPost()}
                <div class="avatar">
                    {$topic->lastPost()->author()->avatar('tiny')|noescape}
                </div>
                <div>
                    {$topic->link($topic->lastPost()->post_id)|noescape}<br>
                    przez {$topic->lastPost()->author()->link()|noescape}
                </div>
                {else}
                <span class="desc">brak postów</span>
                {/if}
            </div>
            {if User::loggedIn()->isAdmin()}
            <div class="admin_edit">
                <a href="?controller=topics&topic_id={$topic->topic_id|noescape}&do=edit">
                    <i class="fas fa-cog"></i>
                </a>
                <a href="?controller=topics&topic_id={$topic->topic_id|noescape}&do=delete">
                    <i class="fas fa-trash"></i>
                </a>
            </div>
            {/if}
        </li>
    {/foreach}
</ol>
{else}
brak tematów
{/if}