<div class="infobox">
    <div class="avatar">
        {$topic->author()->avatar('small')|noescape}
    </div>
    <div class="topic_title">
        <h2>{$topic->title}</h2>
        <span class="desc">napisany przez {$topic->author()->link()|noescape}, {$topic->created}</span>
    </div>
    <div class="admin_controls">
        {if User::loggedIn()->isAdmin()}
        <a href="?controller=topics&do=edit&topic_id={$topic->topic_id}">
            <i class="fas fa-edit"></i>
        </a>
        <a href="?controller=topics&do=delete&topic_id={$topic->topic_id}">
            <i class="fas fa-trash"></i>
        </a>
        {/if}
    </div>
</div>
<div class="posts">
    {foreach $topic->posts() as $post}
    <article class="post" id="post-{$post->post_id}">
        <aside class="author_bar">
            <h4>
                {$post->author()->link()|noescape}
            </h4>
            {$post->author()->avatar('large')|noescape}
            <span class="reputation">
                <i class="fas fa-plus-circle"></i> {$post->author()->reputation()}
            </span>
            <span>
                {$post->author()->group()|noescape}
            </span>

        </aside>
        <div class="post_content">
            <div class="meta desc small">
                <div class="date">Napisano {$post->created}</div>
                {if $post->canEdit()}
                    <div class="admin_controls">
                        <div class="admin_edit">
                            <a href="?controller=posts&post_id={$post->post_id|noescape}&do=edit">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="?controller=posts&post_id={$post->post_id|noescape}&do=delete">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                    </div>
                {/if}
            </div>
            <div class="content">
                {$post->content|noescape}
            </div>
            <div class="reactions">
                {if $post->canReact()}
                    <a href="{$post->reactUrl()}" class="reaction {if $post->reacted()}reacted{/if}">
                        <i class="fas fa-thumbs-up"></i>
                        <span>
                        {if $post->reacted()}
                            Lubisz to!
                        {else}
                            Lubię to!
                        {/if}
                        </span>
                    </a>
                {/if}
                <div class="reputation">
                    <i class="fas fa-plus-circle"></i> {$post->reputation()}
                </div>
            </div>
        </div>
    </article>
    {/foreach}
</div>
<h3>Dodaj nowy post</h3>
{$postForm}
