<div class="controls">
    {if User::loggedIn()->isAdmin()}
        <a href="?controller=forums&do=add" class="button">Dodaj nowe forum</a>
    {/if}
</div>
<ol class="forums">
    {foreach $forums as $forum}
    <li>
        <div class="icon">
            <i class="fas fa-comments"></i>
        </div>
        <div class="forum_info">
            <h4>
                <a href="?controller=forums&forum_id={$forum->forum_id|noescape}">
                    {$forum->name|noescape}
                </a>
            </h4>
            <p>{$forum->description|noescape}</p>
        </div>
        <div class="topics_count">
            <div class="number">{$forum->countTopics()}</div> tematów
        </div>
        <div class="last_poster">
            {if $forum->lastPost()}
                <div class="avatar">
                    {$forum->lastPost()->author()->avatar('tiny')|noescape}
                </div>
                <div>
                    {$forum->lastPost()->topic()->link($forum->lastPost()->post_id)|noescape}<br>
                    przez {$forum->lastPost()->author()->link()|noescape}
                </div>
            {else}
            <span class="desc">brak postów</span>
            {/if}
        </div>
        {if User::loggedIn()->isAdmin()}
            <div class="admin_edit">
                <a href="?controller=forums&forum_id={$forum->forum_id|noescape}&do=edit">
                    <i class="fas fa-cog"></i>
                </a>
                <a href="?controller=forums&forum_id={$forum->forum_id|noescape}&do=delete">
                    <i class="fas fa-trash"></i>
                </a>
            </div>
        {/if}
    </li>
    {/foreach}
</ol>