<div class="member_header">
    <div class="background">
        <div class="avatar">
            {$member->avatar('xlarge')|noescape}
        </div>
        <div class="nickname">
            <div class="nick">{$member->name}</div><br>
            <div class="group">{$member->group()|noescape}</div>
        </div>
    </div>
    <div class="info">
        {if $member->canDelete()}
        <a href="{$member->url()}&do=delete" class="button error">Usuń</a>
        {/if}
        {if $member->canEdit()}
            <a href="{$member->url()}&do=edit" class="button">Edytuj</a>
        {/if}
        {if $member->canFollow()}
            {if $member->isFollowed()}
                <a href="{$member->url()}&do=follow" class="button grey">Przestań obserwować</a>
            {else}
                <a href="{$member->url()}&do=follow" class="button">Obserwuj</a>
            {/if}
        {/if}
        <div class="stat">
            <div class="description">Posty</div>
            <div class="value">{$member->postCount()}</div>
        </div>
        <div class="stat">
            <div class="description">Rejestracja</div>
            <div class="value">{date("F j, Y",strtotime($member->joined))}</div>
        </div>
        <div class="stat">
            <div class="description">Obserwujących</div>
            <div class="value">{$member->followers(true)}</div>
        </div>
        {if User::loggedIn()->isAdmin()}
            <div class="stat">
                <div class="description">Email</div>
                <div class="value">{$member->email}</div>
            </div>
        {/if}
    </div>
</div>
<div class="member_content">
    <aside>
        <div class="reputation {if $member->reputation() > 0}good{/if}">
            <div class="desc">Reputacja</div>
            <div class="number">{$member->reputation()}</div>
        </div>
        <div class="box">
            <h2>Obserwatorzy</h2>
            <div class="box_content">
                {if $member->followers(true) > 0}
                    <div class="avatar_grid">
                        {foreach $member->followers() as $follow}
                        <div class="avatar">
                            {$follow->follower()->avatar('mini')|noescape}
                        </div>
                        {/foreach}
                    </div>
                {else}
                <span class="desc" style="text-align: center; display: block;">Brak obserwatorów!</span>
                {/if}
            </div>
        </div>

        <div class="box">
            <h2>Obserwowani</h2>
            <div class="box_content">
                {if $member->followed(true) > 0}
                <div class="avatar_grid">
                    {foreach $member->followed() as $follow}
                    <div class="avatar">
                        {$follow->followed()->avatar('mini')|noescape}
                    </div>
                    {/foreach}
                </div>
                {else}
                <span class="desc" style="text-align: center; display: block;">Brak obserwatorów!</span>
                {/if}
            </div>
        </div>
    </aside>
    <article>
        {if !empty($member->about)}
            <div class="box">
                <h2>O mnie</h2>
                <div class="box_content">
                    {$member->about|noescape}
                </div>
            </div>
        {/if}
        <div class="box">
            <h2>
                {if User::loggedIn()->isAdmin()}
                    <a href="?controller=trophies&member_id={$member->member_id}&do=add">
                        <i class="fas fa-plus"></i>
                    </a>
                {/if}
                Zdobyte trofea
            </h2>
            <div class="box_content">
                {if $member->trophies(true) > 0}
                    <ol class="trophies">
                        {foreach $member->trophies() as $trophy}
                            <li>
                                <div class="icon">
                                    <i class="fas fa-trophy"></i>
                                </div>
                                <div class="description">
                                    <strong>
                                        {$trophy->description|noescape}
                                    </strong>
                                </div>
                                <div class="giver">
                                    {$trophy->giver()->avatar('mini')|noescape}
                                    {$trophy->giver()->link()|noescape}
                                </div>
                                <div class="date">
                                    {date("F j, Y",strtotime($trophy->give_date))}
                                </div>
                                {if User::loggedIn()}
                                <div class="admin_controls">
                                    <a href="?controller=trophies&trophy_id={$trophy->trophy_id}&do=edit">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a href="?controller=trophies&trophy_id={$trophy->trophy_id}&do=delete">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </div>
                                {/if}

                            </li>
                        {/foreach}
                    </ol>
                {else}
                    <div class="desc">
                        Brak trofeów
                    </div>
                {/if}
            </div>
        </div>
    </article>
</div>
