<!DOCTYPE html>
<html lang="pl" dir="ltr">
<head>
    <meta charset="utf-8">
    {if $title}
    <title>{$title} - Forum</title>
    {/if}
    {foreach $cssFiles as $cssFile}
        <link rel="stylesheet" href="{$cssFile}">
    {/foreach}
</head>
<body class="controller-{$controller}">
{if $header}
{$header|noescape}
{/if}
<div id="wrapper">
    <header class="main-header">
        <div class="branding">
            <div class="main_width">
                <a href="/" id="logo">
                    <img class="home" src="assets/img/logo.png">
                </a>

                <div class="userbar">
                    {if $user}
                        <a href="?controller=member&id={$user->member_id}">
                            {$user->name|noescape}
                        </a> &nbsp;
                        <a href="?controller=logout">Wyloguj</a>
                    {else}
                        <a href="?controller=login">Zaloguj</a>
                    {/if}
                </div>
            </div>
        </div>
        {if $breadcrumb}
        <div class="breadcrumb">
            <div class="main_width">
                <ul>
                    {foreach $breadcrumb as $page}
                    <li>
                        <a href="{$page['url']}">
                            {if $page['url'] == '/'}
                                <i class="fas fa-home"></i>
                            {else}
                                <i class="fas fa-chevron-right"></i>
                            {/if}
                            {$page['name']}
                        </a>
                    </li>
                    {/foreach}
                </ul>
                <div class="search_bar">
                    szukajka
                </div>
            </div>
        </div>
        {/if}
    </header>

    {$output|noescape}
</div>
{if $footer}
{$footer|noescape}
{/if}
{foreach $jsFiles as $jsFile}
<script src="{$jsFile}" charset="utf-8"></script>
{/foreach}
</body>
</html>